service: api-tts
frameworkVersion: '3'

plugins:
  - serverless-deployment-bucket
  - serverless-python-requirements
  - serverless-dotenv-plugin

custom:
  dotenv:
    path: .env

useDotenv: true

provider:
  name: aws
  runtime: python3.9
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - polly:SynthesizeSpeech
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Query
            - s3:*
          Resource: "*"
  deploymentBucket:
    blockPublicAccess: false

functions:
  health:
    handler: handler.health
    events:
      - httpApi:
          path: /
          method: get
  v1Description:
    handler: handler.v1_description
    events:
      - httpApi:
          path: /v1
          method: get
  v2Description:
    handler: handler.v2_description
    events:
      - httpApi:
          path: /v2
          method: get
  v1ttsDescription:
    handler: handler.v1_tts_description
    events:
      - httpApi:
          path: /v1/tts
          method: post
  v2ttsDescription:
    handler: handler.v2_tts_description
    events:
      - httpApi:
          path: /v2/tts
          method: post
  v3ttsDescription:
    handler: handler.v3_tts_description
    events:
      - httpApi:
          path: /v3/tts
          method: post

resources:
  Resources:
    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:BUCKET_NAME}
        
    MyS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref MyS3Bucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: 
                - s3:GetObject
              Resource: 
                - !Sub "arn:aws:s3:::${MyS3Bucket}/*"

    MyDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: "Id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "Id"
            KeyType: "HASH"
        BillingMode: "PAY_PER_REQUEST"
